lowercaseKeywords: true
connections:
  - alias: playground_postgres
    driver: postgresql
    proto: tcp
    user: postgres
    passwd: postgres
    host: 127.0.0.1
    port: 2345
    dbName: postgres
