#!/bin/zsh
# Uncomment to profile zsh startup.
# NOTE: must also uncomment last line.
# zmodload zsh/zprof

export PATH="/usr/local/sbin:$PATH"

PROMPT="%F{blue%}[%D{%H:%M:%S}] %B%F{cyan}%~"$'\n'"%F{yellow}> %b"

# Speed up zsh compinit by only checking cache once a day.
# https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-2308206
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C
# Case insensitive completion
zstyle ':completion:*' menu-select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# Set the command history to a very high value and add to the history immediately.
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
setopt auto_cd
export HISTTIMEFORMAT="[%F %T] "
export XDG_CONFIG_HOME=$HOME/.config

# Set default editor and pager
export EDITOR='nvim'
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Edit line in nvim with ctrl-e
autoload edit-command-line
zle -N edit-command-line

# Add to PATH
fpath=(
  ~/.zsh/funcs
  "${fpath[@]}"
)
autoload -Uz aichat_config
autoload -Uz git_config
autoload -Uz lazygit_config
autoload -Uz font_picker
autoload -Uz dark_mode
autoload -Uz psqlp
autoload -Uz tmux_session_select
autoload -Uz tmuxinator_session_select
autoload -Uz colorscheme_picker
autoload -Uz background_picker
autoload -Uz find_file

# autocompletion using arrow keys (based on history)
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# Alias
alias l="lsd -lah"
alias s="tmux_session_select"
alias ff="find_file"
alias cal="cal -A 1 -B 1"
alias ai="aichat -s"

# Raise max files and max procs
ulimit -n 200000
ulimit -u 2048

# zsh plugins
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# fzf
export FZF_DEFAULT_OPTS="
  --history=$HOME/.fzf_history_dir
  --bind=ctrl-n:down
  --bind=ctrl-p:up
  --bind=ctrl-d:preview-half-page-down
  --bind=ctrl-u:preview-half-page-up
  --bind=ctrl-i:previous-history
  --bind=ctrl-o:next-history
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  $FZF_DEFAULT_OPTS"
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}' \
  --bind=ctrl-n:down
  --bind=ctrl-p:up
  --bind=ctrl-d:preview-half-page-down
  --bind=ctrl-u:preview-half-page-up
  --bind=ctrl-i:previous-history
  --bind=ctrl-o:next-history
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy path into clipboard'"
export FZF_CTRL_R_OPTS="
  --preview 'echo {}'
  --preview-window up:3:hidden:wrap
  --bind=ctrl-n:down
  --bind=ctrl-p:up
  --bind=ctrl-i:previous-history
  --bind=ctrl-o:next-history
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
export FZF_ALT_C_COMMAND='fd -t d . ~'
export FZF_HISTORY_DIR=1

# zsh-vi-mode will overwrite keybindings unless they are added to `zvm_after_init_commands`.
# https://github.com/jeffreytse/zsh-vi-mode?tab=readme-ov-file#execute-extra-commands
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

function zvm_after_init() {
  bindkey '^o' edit-command-line
  bindkey '^f' fzf-file-widget
}

# python
path+=$HOME/.pyenv/bin
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# ChatGPT
OPENAI_API_KEY_FILE=$HOME/.openai_api_key
if [ -f $OPENAI_API_KEY_FILE ]; then
  export OPENAI_API_KEY=$(cat $OPENAI_API_KEY_FILE)
else
  export OPENAI_API_KEY=""
fi

# Rancher
export PATH="$HOME/.rd/bin:$PATH"

# Uncomment to profile zsh startup.
# NOTE: must also uncomment first line.
# zprof
