#!/bin/zsh
# Uncomment to profile zsh startup.
# NOTE: must also uncomment last line.
# zmodload zsh/zprof

# Set the command history to a very high value and add to the history immediately.
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "

# Automatically update the NVIM_PIPE env var in all panes of a tmux session if it is changed.
# NOTE: Comment this block out and `source ~/.zshrc` if this behavior needs to be temporarily turned off.
autoload -U add-zsh-hook
update_nvim_pipe() {
    local var
    var=$(tmux show-environment | grep '^NVIM_PIPE=')
    if [ "$?" -eq 0 ]; then
        eval "$var"
    else
        unset NVIM_PIPE
    fi
}
if [[ -n "$TMUX" ]]; then
    add-zsh-hook preexec update_nvim_pipe
fi

# Set default editor and pager
if [[ "$(command -v nvim)" ]]; then
    export EDITOR='nvim'
    export MANPAGER='nvim +Man!'
    export MANWIDTH=999
fi

# Add to PATH
path+=$HOME/.local/bin
path+=$HOME/.local/bin/neovim/bin
fpath+=$HOME/.zsh/compdef/

# Download Znap, if it's not there yet.
[[ -f ~/Git/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ~/Git/zsh-snap

source ~/Git/zsh-snap/znap.zsh  # Start Znap

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle :prompt:pure:git:stash show yes
znap prompt sindresorhus/pure
znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-autosuggestions

# autocompletion using arrow keys (based on history)
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# Alias
alias ls="ls --color=always -lah"
alias vim="nvim"
alias h="cht.sh"
alias top="htop"
alias s="tmuxinator start"
alias rg="rg -L"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# google-cloud-sdk completions
# source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
#
# python
path+=$HOME/.pyenv/bin
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Raise max files and max procs
ulimit -n 200000
ulimit -u 2048

# ChatGPT
OPENAI_API_KEY_FILE=$HOME/.openai_api_key
if [ -f $OPENAI_API_KEY_FILE ]; then
    export OPENAI_API_KEY=$(cat $OPENAI_API_KEY_FILE)
else
    export OPENAI_API_KEY=""
fi

# Uncomment to profile zsh startup.
# NOTE: must also uncomment first line.
# zprof
export PATH="/usr/local/sbin:$PATH"
