[bar.default]
background_opacity = 0.4999999888241291
center = [ "launcher" ]
end = [ "date", "battery", "control-center" ]
margin_edge = 4
margin_ends = 8
padding = 16
position = "bottom"
radius = 50
start = [ "taskbar" ]
widget_spacing = 12

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "caffeine"

[dock]
auto_hide = true
reserve_space = false
show_dots = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1746.0
    cy = 1845.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[shell.animation]
enabled = false
speed = 2.500000037252903

[shell.panel]
launcher_categories = false
launcher_compact = true
launcher_placement = "attached"
launcher_session_search = true
open_near_click_control_center = true

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/ryanburda/code/assets/base/assets/backgrounds"
transition = [ "disc", "fade", "wipe" ]
transition_duration = 400
transition_on_startup = true

    [wallpaper.default]
    path = "/home/ryanburda/code/assets/base/assets/backgrounds/cabin-night-sky.jpg"

    [wallpaper.last]
    path = "/home/ryanburda/code/assets/base/assets/backgrounds/cabin-night-sky.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/ryanburda/code/assets/base/assets/backgrounds/cabin-night-sky.jpg"

[widget.battery]
show_label = false

[widget.clock]
format = "{:-%I:%M}"

[widget.date]
format = "{:%-m/%d %-I:%M}"

[widget.network]
show_label = false

[widget.taskbar]
group_by_workspace = true
inactive_opacity = 0.69999999999999996
scale = 1.1500000000000001

[widget.volume]
show_label = false