syntax enable
colorscheme desert

set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set encoding=utf-8

set nowrap
set number
set relativenumber
set hlsearch
highlight LineNr ctermfg=grey

set colorcolumn=120
highlight ColorColumn ctermbg=DarkGrey

set whichwrap+=>,l
set whichwrap+=<,h
set whichwrap+=[,]

autocmd FileType make set noexpandtab shiftwidth=4 softtabstop=0
