[colors.primary]
background = '#f5f2ee'
foreground = '#010409'
[colors.normal]
black      = '#e1c595'
blue       = '#0349b4'
cyan       = '#1b7c83'
green      = '#024c1a'
magenta    = '#622cbc'
red        = '#a0111f'
white      = '#6b4542'
yellow     = '#3f2200'
[colors.bright]
black      = '#4b535d'
blue       = '#1168e3'
cyan       = '#1b7c83'
green      = '#055d20'
magenta    = '#622cbc'
red        = '#86061d'
white      = '#66707b'
yellow     = '#4e2c00'
[colors.cursor]
cursor     = '#0e1116'
text       = '#ffffff'
