[colors.primary]
background = '#11191E'
foreground = '#d8dee9'
[colors.normal]
black      = '#112233'
blue       = '#81a1c1'
cyan       = '#88c0d0'
green      = '#a3be8c'
magenta    = '#b48ead'
red        = '#bf616a'
white      = '#e5e9f0'
yellow     = '#ebcb8b'
[colors.bright]
black      = '#4c566a'
blue       = '#81a1c1'
cyan       = '#8fbcbb'
green      = '#a3be8c'
magenta    = '#b48ead'
red        = '#bf616a'
white      = '#eceff4'
yellow     = '#ebcb8b'
