name: config
root: ~/Developer/config

windows:
  - main:
      layout: even-vertical
      panes:
        - vim
        - terminal:
          - tmux resize-pane -t 1 -y 10
          - clear
  - home:
      layout: even-vertical
      root: ~/
      panes:
        - #empty
