#!/bin/zsh
# Creates the aichat config yaml based off templated values

LIGHT_OR_DARK=$(cat $XDG_CONFIG_HOME/nvim/.background)

if [[ "$LIGHT_OR_DARK" == "light" ]]; then
    export AICHAT_LIGHT_THEME="true"
else
    export AICHAT_LIGHT_THEME="false"
fi

OPENAI_API_KEY=$(cat $HOME/.openai_api_key)

if [[ $OSTYPE == darwin* ]]; then
    # macOS
    envsubst < "${XDG_CONFIG_HOME}/aichat/aichat_config.yaml.template" > "${HOME}/Library/Application Support/aichat/config.yaml"
else
    # linux
    envsubst < "${XDG_CONFIG_HOME}/aichat/aichat_config.yaml.template" > "${XDG_CONFIG_HOME}/aichat/config.yaml"
fi

