#!/bin/zsh

# open the file in the current tmux session's nvim instance if one exists, else open it in a new nvim instance.
FILE=$1
NVIM_PIPE=$(tse NVIM_PIPE)

if [[ -n "$TMUX" ]] && [[ ! -z "${NVIM_PIPE}" ]]; then
    nvim --server $NVIM_PIPE --remote $FILE
else
    nvim $FILE
fi
