#!/bin/zsh

# bring up all entries in the pgpass file.
# open the selected entry in psql
db_connections=$(awk '!/^#|^$/' ~/.pgpass)
selection=$(echo $db_connections | awk -F: '{ $3=""; print }' | fzf)

h=$(echo $selection | awk '{print $1}')
p=$(echo $selection | awk '{print $2}')
d=$(echo $selection | awk '{print $3}')
u=$(echo $selection | awk '{print $4}')

psql -h $h -p $p -d $d -U $u
