#!/bin/zsh

# A psql connection picker

# bring up all entries in the pgpass file.
# open the selected entry in psql
db_connections=$(awk '!/^#|^$/' ~/.pgpass)
selection=$(echo $db_connections | awk -F':' '{ $5=""; print }' | sort | fzf)

if [[ -z "${selection}" ]]; then
    return 0
fi

h=$(echo $selection | awk '{print $1}')
p=$(echo $selection | awk '{print $2}')
d=$(echo $selection | awk '{print $3}')
u=$(echo $selection | awk '{print $4}')

psql -h $h -p $p -d $d -U $u
