#!/bin/zsh

# NAME
#   select_active_session - switches between active tmux sessions.
#
# SYNOPSIS
#   select_active_session

list_sessions() {
    tmux ls | awk -F: '{print $1}' | sort -u
}

while true; do
    SESSION=$(list_sessions | \
              fzf --cycle \
                  --bind "ctrl-x:execute(tmux kill-session -t {})+clear-query+reload($(declare -f list_sessions); list_sessions)" \
                  --bind "tab:execute(tmux switch-client -l)+abort" \
                  --header "ctrl-x: kill-session, tab: previous-session")

    if [[ -z $SESSION ]]; then
        break
    else
        tmux switch-client -t $SESSION
        return 0
    fi

done
