#!/bin/zsh

# NAME
#   select_active_session - switches between active tmux sessions.
#
# SYNOPSIS
#   select_active_session
while true; do
    # TODO: get rid of duplication between original call to fzf and reload().
    SESSION=$(tmux ls | awk -F: '{print $1}' | sort -u | fzf --cycle \
                                                             --bind 'ctrl-x:execute(tmux kill-session -t {})+clear-query+reload(tmux ls | awk -F: '\''{print $1}'\'' | sort -u)')

    if [[ -z $SESSION ]]; then
        break
    else
        tmux switch-client -t $SESSION
        return 0
    fi

done
