#!/bin/zsh

# The '\' before ls makes sure it avoids any aliases.
SESSION=$(\ls ~/.config/tmuxinator/ | awk -F '.' '{print $1}' | fzf)
if [[ ! -z "${SESSION}" ]]; then
    tmuxinator start $SESSION
fi
