# Automatically start a tmux session
if [ "$TMUX" = "" ]; then tmux; fi

# Set default editor
export EDITOR=nvim

# Add to PATH
path+=$HOME/.local/bin
path+=$HOME/.local/bin/neovim/bin
fpath+=$HOME/.zsh/compdef/

# Pure theme
fpath+=/opt/homebrew/share/zsh/site-functions
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:stash show yes
prompt pure

# Source zsh plugins
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    autoload -Uz compinit
    compinit -i
    zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
fi
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Alias
alias ls="ls --color=always -lah"
alias vim="nvim"
alias h="cht.sh"
alias top="htop"
alias s="tmuxinator start"

# C-k usually does delete all after cursor but this has been remapped to
# move between tmux panes. Bind this to ctrl-backspace instead.
bindkey '^]' kill-line
bindkey '^[' backward-kill-line

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# google-cloud-sdk completions
source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# python
path+=$HOME/.pyenv/bin
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Raise max files and max procs
ulimit -n 200000
ulimit -u 2048
