# name for your ranked palette
#
# slot 0 = black
# slot 1 = red
# slot 2 = green
# slot 3 = yellow
# slot 4 = blue
# slot 5 = magenta
# slot 6 = cyan
# slot 7 = white

gui:
  theme:
    activeBorderColor:
      - red
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - black
  enlargedSideViewLocation: 'top'
  showCommandLog: false
  showIcons: true
  scrollPastBottom: false
  branchColors:
    'main': red
    'master': red
    'develop': green
  authorColors:
    '*': blue
git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --line-numbers
promptToReturnFromSubprocess: false
customCommands:
  - key: 'o'
    command: "nvim {{.SelectedFile.Name}}"
    context: 'files'
    description: 'Open file in Neovim'
    output: terminal
  - key: 'D'
    command: "nvim -c 'DiffviewOpen {{.SelectedLocalBranch.Name}}'"
    context: 'localBranches'
    description: 'Open diff of current branch to selected branch'
    output: terminal
  - key: 'D'
    command: "nvim -c 'DiffviewOpen {{.SelectedRemoteBranch.Name}}'"
    context: 'remoteBranches'
    description: 'Open diff of current branch to selected branch'
    output: terminal
  - key: 'D'
    command: "nvim -c 'DiffviewOpen {{.SelectedLocalCommit.Sha}}'"
    context: 'commits'
    description: 'Open diff of current branch to selected commit'
    output: terminal
  - key: 'S'
    command: "git fetch -p"
    context: 'remoteBranches'
    description: 'Prune local branches that are no longer in remote (Sync)'
